fix_: 5

diff --git a/.github/workflows/commits.yml b/.github/workflows/commits.yml
--- a/.github/workflows/commits.yml
+++ b/.github/workflows/commits.yml
@@ -19,14 +19,44 @@ jobs:
           ref: ${{ env.GITHUB_HEAD_REF }}
           fetch-tags: true
 
-      - name: Fetch tags
+      # - name: Fetch tags
+      #   run: |
+      #     git fetch --tags --quiet
+      #     echo "1 - ${{ github.event.pull_request.head.ref }}"
+      #     echo "2 - ${{ github.event.pull_request.base.ref }}"
+      #     echo "3 - ${{ env.GITHUB_HEAD_REF }}"
+      #     echo "4 - origin/${GITHUB_HEAD_REF}"
+      #     git checkout ${{ github.event.pull_request.head.ref }}
+
+
+      - name: Check commit message
+        id: check_commit_message
         run: |
-          git fetch --tags --quiet
-          echo "1 - ${{ github.event.pull_request.head.ref }}"
-          echo "2 - ${{ github.event.pull_request.base.ref }}"
-          echo "3 - ${{ env.GITHUB_HEAD_REF }}"
-          echo "4 - origin/${GITHUB_HEAD_REF}"
-          git checkout ${{ github.event.pull_request.head.ref }}
+          set +e
+
+          output=$(./commit_check.sh 2>&1)
+          exit_code=$?
+          
+          echo "${output}" | sed '$d'
+          echo "has_breaking_changes=${has_breaking_changes}"
+          
+          echo "exit_code=${exit_code}" >> $GITHUB_OUTPUT
+          
+          has_breaking_changes=$(echo "${output}" | tail -n 1)
+          echo "has_breaking_changes=${has_breaking_changes}" >> $GITHUB_OUTPUT
+          
+          invalid_commit_messages=$(echo "${output}" | sed '1d;$d')
+          invalid_commit_messages=$(echo "${output}" | sed '1d;$d')
+          invalid_commit_messages=$(echo "${invalid_commit_messages}" | sed 's/\x1b\[[0-9;]*m//g') # Remove color codes
+          invalid_commit_messages=$(echo "${invalid_commit_messages}" | sed 's/^Commit message is ill-formed: //') # Remove prefix
+          
+          if [[ $exit_code -ne 0 ]]; then
+            EOF=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)
+            echo "error_message<<$EOF" >> "$GITHUB_ENV"
+            echo "${invalid_commit_messages}" >> "$GITHUB_ENV"
+            echo "$EOF" >> "$GITHUB_ENV"
+          
+          fi
 
       - name: "Comment"
         uses: marocchino/sticky-pull-request-comment@v2
